refresh token
MarinaTripetska/slim-mom-back pull request #27
Opened 2022-07-29 13:52 UTC by IlchenkoY

2022-07-29 19:50 UTC, MarinaTripetska requested changes

2022-07-29 19:50 UTC, MarinaTripetska commented on controllers/auth/current.js
> +        tokens,
перепиши будь ласка tokens над юзером, як у відповіді логіна, щоб було таке саме. :)

2022-07-29 19:50 UTC, MarinaTripetska commented on controllers/auth/refreshToken.js
> +  const tokens = await updateTokens(userId);
сюди SECRET_KEY вже не треба передавати?

2022-07-29 19:50 UTC, MarinaTripetska commented on models/user.js
> +    tokens: {
тут можна розписати які поля в обєкті?

2022-07-29 19:50 UTC, MarinaTripetska commented on routes/api/auth.js
> +router.post("/refresh-tokens", ctrlWrapper(ctrl.refreshTokens));
ctrlWrapper(auth) тут не потрібен?

2022-07-29 19:52 UTC, MarinaTripetska commented on controllers/auth/refreshToken.js
> +  const tokens = await updateTokens(userId);
вже знаю що не треба :)

2022-07-29 20:30 UTC, IlchenkoY commented on controllers/auth/current.js
> +        tokens,
Done

2022-07-29 20:31 UTC, IlchenkoY commented on controllers/auth/refreshToken.js
> +  const tokens = await updateTokens(userId);
Done

2022-07-29 20:52 UTC, IlchenkoY commented on routes/api/auth.js
> +router.post("/refresh-tokens", ctrlWrapper(ctrl.refreshTokens));
ctrlWrapper(auth) не нужен, так как в контроллере refreshTokens есть отдельная верификация.

2022-08-14 21:44 UTC, MarinaTripetska approved these changes

2022-08-14 21:44 UTC, merged